from django.db import models


# Create your models here.
class Proverb(models.Model):
    category = models.CharField(max_length=30)
    text = models.CharField(max_length=200)


class Person(models.Model):
    """
    Person model.
    In separate view, model is generated by getting form inputs.
    """
    selected_proverb = models.CharField(max_length=200)
    age = models.IntegerField()
    gender = models.CharField(max_length=1)

    def __str__(self):
        return 'Model class for Person'

    def find_category(self):
        # load all proverbs
        all_proverbs = Proverb.objects.all()
        print(self.selected_proverb)
        print(all_proverbs)